global:
  scrape_interval: 15s   # How frequently to scrape targets. Default is every 1 minute.
  evaluation_interval: 15s   # How frequently to evaluate rules. Default is every 1 minute.

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']   # Target to scrape. Replace 'localhost' with your actual host or IP.

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node_exporter:9100'] 
